# -*- coding: utf-8 -*-
"""note_session_16(RandomForestRegressor).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CrZAl2xQDt72tfzPnFuOhluOnyXyqbhQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Position_Salaries.csv')
dataset

x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

"""training random forest"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10,random_state= 42)
regressor.fit(x,y)

"""predict new result

"""

regressor.predict([[6.5]])

