# -*- coding: utf-8 -*-
"""note session 15(Decision Tree Regression).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qpxuiF5HBk66MgQkXe8qA9wl3RgkO9G

#Decision Tree Regression
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Position_Salaries.csv')
dataset.info()

dataset

#لازم رينج
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1]

from sklearn.tree import DecisionTreeRegressor
regreesor = DecisionTreeRegressor()
regreesor.fit(x,y)

from sklearn.tree import export_text
text = export_text(regreesor)

print(text)

"""prediciting new result"""

regreesor.predict([[3.2]])

xGrid= np.arange(min(x),max(x),0.02)
xGrid = xGrid.reshape((len(xGrid),1))
plt.scatter(x,y,color='red')
plt.plot(xGrid,regreesor.predict(xGrid),color='blue')

