# -*- coding: utf-8 -*-
"""note session 13(sklearn).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wn5ZTosDqDgCi2zlYMP_7b30RQW3myiG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Salary_Data.csv')
dataset

dataset.info()

x= dataset.iloc[:,0:-1]
y =dataset.iloc[:,-1]

x

y

from sklearn.model_selection import train_test_split
xTrain , xTest , yTrain , yTest = train_test_split(x,y,test_size=1/3)

"""###Training linear regression on training set
هنعلم المودل
"""

from sklearn.linear_model import  LinearRegression
reg = LinearRegression()
reg.fit(xTrain,yTrain)

"""####predict on test set"""

yPred = reg.predict(xTest)

"""####visualisaing traing set"""

#True Data
plt.scatter(xTrain,yTrain,color= 'red')
#predict
plt.plot(xTrain,reg.predict(xTrain),color= 'blue')
plt.title('salary vs years of Expercience')
plt.xlabel('years of Expercience')
plt.ylabel('salary')
plt.show()

"""####visualize test set"""

plt.scatter(xTest,yTest,color='red')
plt.plot(xTrain,reg.predict(xTrain),color='blue')
#نفس الخط
plt.show()

