# -*- coding: utf-8 -*-
"""note session 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dii6zEeXaj3-mJT49mCBKNkdj-Q5j71j
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""import Dataset"""

dataset = pd.read_csv('50_Startups.csv')
dataset.head()

dataset.info()

x = dataset.iloc[:,:-2].values
y = dataset.iloc[:,-1].values

"""split dataset to train and test

"""

from sklearn.model_selection import train_test_split
xTrain , xTest , yTrain,yTest = train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(xTrain,yTrain)

"""predict test set"""

yPred = reg.predict(xTest)

np.set_printoptions(precision=2)
print(np.concatenate((yPred.reshape(len(yPred),1),yTest.reshape(len(yTest),1)),1))

